.Dd March 03, 2014
.Dt EC2-BACKUP 1
.Os
.Sh NAME
.Nm ec2-backup
.Nd backup a directory into Elastic Block Storage (EBS)
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl m Ar method
.Op Fl v Ar volume-id
.Ar dir
.Sh DESCRIPTION
The
.Nm
tool performs a backup of the given directory into Amazon Elastic Block
Storage (EBS).
This is achieved by creating a volume of the appropriate size, attaching
it to an EC2 instance and finally copying the files from the given
directory into this volume.
.Sh OPTIONS
.Nm
accepts the following command-line flags:
.Bl -tag -width _v_volume_id
.It Fl h
Print a usage statement and exit.
.It Fl m Ar method
Use the given method to perform the backup.
Valid methods are 'dd' and 'rsync'; default is 'dd'.
.It Fl v Ar volume-id
Use the given volume instead of creating a new one.
.El
.Sh DETAILS
.Nm
will perform a backup of the given directory to an ESB volume.
The backup is done in one of two ways: via direct write to the volume as a
block device (utilizing
.Xr tar 1
on the local host and
.Xr dd 1
on the remote instance), or via a (possibly incremental) filesystem sync
(utilizing
.Xr rsync 1 Ns ).
.Pp
Unless the
.Fl v
flag is specified,
.Nm
will create a new volume, the size of which will be at least two times the
size of the directory to be backed up.
.Pp
.Nm
will create an instance suitable to perform the backup, attach the volume
in question and then back up the data from the given directory using the
specified method and then shut down and terminate the instance it created.
.Sh OUTPUT
Unless the
.Ar EC2_BACKUP_VERBOSE
environment variable is set,
.Nm
will not generate any output unless any errors are encountered.
Otherwise, it may print out some useful information about what steps it
is currently performing.
.Pp
Any errors encountered cause a meaningful error message to be printed to
STDERR.
.Sh ENVIRONMENT
.Nm
assumes that the user has set up their environment for general use with
the EC2 tools.
That is, it will not set or modify the variables AWS_CONFIG_FILE, EC2_CERT,
EC2_HOME or EC2_PRIVATE_KEY.
.Pp
.Nm
allows the user to add custom flags to the commands related to starting a
new EC2 instance via the
.Ar EC2_BACKUP_FLAGS_AWS
environment variable.
.Pp
.Nm
also assumes that the user has set up their
.Ar ~/.ssh/config
file to access instances in EC2 via
.Xr ssh 1
without any additional settings.
It does allow the user to add custom flags to the
.Xr ssh 1
commands it invokes via the
.Ar EC2_BACKUP_FLAGS_SSH
environment variable.
.Pp
As noted above, the
.Ar EC2_BACKUP_VERBOSE
variable may cause
.Nm
to generate informational output as it runs.
.Sh EXIT STATUS
The
.Nm
will exit with a return status of 0 under normal circumstances.
If an error occurred,
.Nm
will exit with a value >0.
.Sh EXAMPLES
The following examples illustrate common usage of this tool.
.Pp
To back up the entire filesystem using
.Xr rsync 1 Ns :
.Bd -literal -offset indent
ec2-backup -m rsync /
.Ed
.Pp
To create a complete backup of the current working directory using
defaults (and thus not requiring a filesystem to exist on the volume) to
the volume with the ID vol-1a2b3c4d:
.Bd -literal -offset indent
ec2-backup -v vol-1a2b3c4d .
.Ed
.Pp
Suppose a user has their ~/.ssh/config set up to use the private key
.Ar ~/.ec2/stevens
but wishes to use the key
.Ar ~/.ssh/ec2-key
instead:
.Bd -literal -offset indent
export EC2_BACKUP_FLAGS_SSH="-i ~/.ssh/ec2-key"
ec2-backup .
.Ed
.Pp
To force creation of an instance type of
.Ar t1.micro
instead of whatever defaults might apply
.Bd -literal -offset indent
export EC2_BACKUP_FLAGS_AWS="--instance-type t1.micro"
ec2-backup .
.Ed
.Sh SEE ALSO
aws help,
.Xr dd 1 ,
.Xr tar 1 ,
.Xr rsync 1
.Sh HISTORY
.Nm
was originally assigned by
.An Jan Schaumann
.Aq jschauma@cs.stevens.edu
as a homework assignment for the class "Aspects of System Administration" at
Stevens Institute of Technology in the Spring of 2011.
