.Dd April 17, 2023
.Dt EC2-RESTORE 1
.Os
.Sh NAME
.Nm ec2-restore
.Nd restore data from an EC2 EBS volume
.Sh SYNOPSIS
.Nm
.Op Fl hv
.OP Fl r Ar region
.Op Fl s Ar size
.Fl k Ar keyname
.Ar volume-id
.Sh DESCRIPTION
The
.Nm
restores data from an Amazon EC2 Elastic Block Storage
volume that was backed up using the approach used by
e.g.,
.Xr ec2-backup 1 .
.Sh OPTIONS
.Nm
accepts the following command-line flags:
.Bl -tag -width _k_keyname_
.It Fl h
Print a usage statement and exit.
.It Fl k Ar keyname
Specify the name of the AWS SSH keypair to use when
creating instances.
.It Fl r Ar region
Specify the AWS region explicitly.
If not specified, the user's default region as per
their AWS configuration is used.
.It Fl s Ar size
Only read
.Ar size
bytes from the volume.
.It Fl v
Be verbose and print diagnostic messages to stderr.
.El
.Sh DETAILS
.Xr ec2-backup 1
describes a method of backing up data into an EBS
volume that, in a nutshell, writes the data in
question to the raw device.
.Nm
allows for easy data restoration by performing the
inverse operation.
.Pp
In particular,
.Nm
will create an EC2 instance, attach the specified
volume to the new instance, and then use
.Xr ssh 1
to connect to the instance and read the data from the
raw device using
.Xr dd 1 .
.Pp
In other words,
.Nm
effectively performs the same actions as the following
sequence of commands:
.Bd -literal -offset indent
aws ec2 run-instances
aws ec2 attach-volume
ssh ec2-instance "dd if=/dev/xbd2d"
.Ed
.Pp
Here, "/dev/xbd2d" stands for the suitable raw disk
device, which may differ depending on the instance
type.
.Pp
After all data is read,
.Nm
will terminate the instance it created.
.Pp
.Nm
will not create or modify any other AWS resources.
.Pp
Unless the
.Fl v
flag is specified,
.Nm
will not generate any other output unless any errors are encountered.
If
.Fl v
is specified,
.Nm
may print out some useful information about what steps it is currently
performing to stderr.
.Pp
.Nm
generates the data found on the volume on stdout.
Any errors encountered cause a meaningful error message to be printed to
STDERR.
.Pp
Unless the
.Fl s
flag is given,
.Nm
will read all data from the given volume.
Otherwise, it will read only
.Ar size
bytes, where
.Ar size
may be specified as a total number of bytes, or using
a common unit suffix (e.g., 1K, 2M, 3G to represent 1
kilobyte, 2 megabytes, or 3 gigabytes respectively).
.Sh ENVIRONMENT
.Nm
assumes that the user has set up their environment for
general use with the EC2 command-line tools, and it
will not set nor modify any related environment
variables nor write to any files
.Pp
.Nm
further assumes that the user has set up their
.Ar ~/.ssh/config
file to access instances in EC2 via
.Xr ssh 1
without any additional settings.
It does allow the user to add custom flags to the
.Xr ssh 1
commands it invokes via the
.Ar EC2_RESTORE_FLAGS_SSH
environment variable.
.Sh EXIT STATUS
The
.Nm
will exit with a return status of 0 under normal circumstances.
If an error occurred,
.Nm
will exit with a value >0.
.Sh EXAMPLES
The following examples illustrate common usage of this tool.
.Pp
To write the raw data from the remote volume to a
local file:
.Bd -literal -offset indent
$ ec2-restore -k default vol-1a2b3c4d > data
.Ed
.Pp
To count the number of lines of the first 100
megabytes of the data on the remote volume while
showing debugging information:
.Bd -literal -offset indent
$ ec2-restore -v -k mykey -s 100M vol-1a2b3c4d | wc -l
=> Verifying volume...
=> Volume vol-1a2b3c4d is in availability zone 'us-east-1a'.
=> Creating a suitable instance in 'us-east-1a'...
=> Attaching volume vol-1a2b3c4d to instance i-123abcd456...
=> Reading 100M bytes of data...
        123456
=> Terminating instance i-123abcd456...
.Ed
.Pp
Note: messages prefixed with "=>" are printed to stderr.
.Pp
Suppose a user has their ~/.ssh/config set up to use the private key
.Ar ~/.ec2/stevens
but wishes to use the key
.Ar ~/.ssh/ec2-key
instead, restoring data from a volume in the
`eu-west-3` region:
.Bd -literal -offset indent
$ export EC2_RESTORE_FLAGS_SSH="-i ~/.ssh/ec2-key"
$ ec2-restore -k mykey -r eu-west-3 vol-1a2b3c4d | tar xf -
.Ed
.Sh SEE ALSO
aws help,
.Xr ec2-backup 1 ,
.Xr dd 1 ,
.Xr ssh 1
.Sh HISTORY
.Nm
was originally assigned by
.An Jan Schaumann
.Aq jschauma@stevens.edu
as a homework assignment for the class "Aspects of System Administration" at
Stevens Institute of Technology in the Spring of 2023.
